// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';
import {main} from '../models';

export function GetType(arg1:string):Promise<utils.ExtractedType>;

export function Greet(arg1:string):Promise<string>;

export function OpenSchemaFile():Promise<main.SchemaResult>;

export function ToGQLType(arg1:utils.ExtractedType):Promise<string>;
